### ISSUE TITLE
Error when deserialising a Reference<List<?>>

### ISSUE THREAD

**Issue by WithoutAName25** [dzikoysk/cdn#108]
When I try to load a config file with an Element of the type `Reference<List<?>>`  with `cdn.load()`, I get an Exception. If the type is just `List<?>` everything works fine and other reference-elements are working too.
The error occurs only since version 1.13.0.

The error is that the `defaultValue` that is passed to `ListComposer.deserialize()` is of the type `Reference<List<?>>` and should be of the type `List<?>`.

```
Exception in thread "main" java.lang.ClassCastException: class panda.std.reactive.Reference cannot be cast to class java.util.List (panda.std.reactive.Reference is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
	at net.dzikoysk.cdn.serdes.composers.ListComposer.deserialize(ListComposer.java:38)
	at net.dzikoysk.cdn.serdes.composers.ReferenceComposer.lambda$deserialize$0(ReferenceComposer.java:39)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.serdes.composers.ReferenceComposer.deserialize(ReferenceComposer.java:39)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserializeMember$3(CdnDeserializer.java:103)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeMember(CdnDeserializer.java:103)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeToSection(CdnDeserializer.java:68)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:50)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserialize$1(CdnDeserializer.java:45)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:45)
	at net.dzikoysk.cdn.serdes.composers.ContextualComposers.deserialize(ContextualComposers.java:36)
	at net.dzikoysk.cdn.serdes.composers.ReferenceComposer.lambda$deserialize$0(ReferenceComposer.java:39)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.serdes.composers.ReferenceComposer.deserialize(ReferenceComposer.java:39)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.lambda$deserializeMember$3(CdnDeserializer.java:103)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeMember(CdnDeserializer.java:103)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserializeToSection(CdnDeserializer.java:68)
	at net.dzikoysk.cdn.serdes.CdnDeserializer.deserialize(CdnDeserializer.java:50)
	at net.dzikoysk.cdn.Cdn.lambda$load$1(Cdn.java:87)
	at panda.std.Result.flatMap(Result.java:124)
	at net.dzikoysk.cdn.Cdn.load(Cdn.java:87)
	at eu.withoutaname.discordbots.withoutabot.WithoutABotFactory.createWithoutABot(WithoutABotFactory.kt:17)
	at eu.withoutaname.discordbots.withoutabot.WithoutABotLauncher.create(WithoutABotLauncher.kt:13)
	at eu.withoutaname.discordbots.withoutabot.WithoutABotLauncherKt.main(WithoutABotLauncher.kt:18)
```

**Comment by dzikoysk** [comment]
I can confirm I've successfully reproduced this issue and I'm going to start working on a fix, thanks for reporting this problem!
